SCREEN_WIDTH = 800
SCREEN_HEIGHT= 600

CARD_WIDTH = 350
CARD_HEIGHT = 220
GAP = 40
CARD_COLOR = (255,255,255)

TOTAL_BLOCK_HEIGHT = (CARD_HEIGHT * 2) + GAP
VERTICAL_START = (SCREEN_HEIGHT - TOTAL_BLOCK_HEIGHT) // 2

Y_TOP = VERTICAL_START
Y_BOTTOM = VERTICAL_START + CARD_HEIGHT + GAP

X_CENTER = (SCREEN_WIDTH - CARD_WIDTH) // 2

Y_POSITIONS = {
    "top": Y_TOP,
    "bottom": Y_BOTTOM
}